# Generated by Django 2.1.2 on 2018-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='anio_escolar',
            field=models.CharField(default='2018', max_length=4),
        ),
        migrations.AlterField(
            model_name='anio_academico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
