# Generated by Django 2.1.2 on 2018-11-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0002_auto_20181128_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grado',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
