# Generated by Django 2.1.2 on 2018-11-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ano_escola', models.CharField(max_length=4)),
                ('inst_edu', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('nota_num', models.CharField(max_length=2)),
                ('nota_char', models.CharField(max_length=50)),
            ],
        ),
    ]
