# Generated by Django 2.1.2 on 2018-11-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_maricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
