# Generated by Django 2.1.2 on 2018-11-28 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0003_auto_20181128_1534'),
        ('boletin', '0003_auto_20181119_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='matricula_cn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tercero.curso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tercero.matricula')),
            ],
        ),
    ]
